### ISSUE TITLE
Bug: This page has crashed

### ISSUE THREAD

**Issue by kderck** [doitintl/help#142]
While using Safari (Version 15.3 (17612.4.9.1.8)) while browsing from the homepage going to `AWS Lens` I get `This page crashed`. 

<img width="1512" alt="Screenshot 2022-07-14 at 15 29 54" src="https://user-images.githubusercontent.com/98526301/179009420-2174fdf3-15e4-4c33-af17-0e921ae88f80.png">

<img width="1512" alt="Screenshot 2022-07-14 at 15 30 00" src="https://user-images.githubusercontent.com/98526301/179009407-a11e6b08-1a3a-4b3c-ae18-210a969bfb04.png">

I also get this error when going to flexisave from the developer documentation.

<img width="1512" alt="Screenshot 2022-07-14 at 15 42 48" src="https://user-images.githubusercontent.com/98526301/179009842-091e7071-9f2e-4a46-b719-399cb5c08ddf.png">

**Comment by norosa** [comment]
@kderck thanks for the bug report! I am unable to reproduce. I am thinking that you may have caught the site just after deployment and some caching issue is the root cause. Can you try to access the page again in a private window and let me know what you see?

**Comment by kderck** [comment]
Hi @norosa this is in a private window. 
<img width="1512" alt="Screenshot 2022-07-14 at 16 53 47" src="https://user-images.githubusercontent.com/98526301/179024809-7bbf25db-252d-414a-84f1-fcc85a11eaf8.png">

**Comment by kderck** [comment]
This works fine in Google Chrome. But looks to be an issue on MacOS Safari - I've just tried on my MacBook Air with the same issue.
<img width="1512" alt="Screenshot 2022-07-14 at 16 55 02" src="https://user-images.githubusercontent.com/98526301/179025085-3614c1fc-a00e-4281-a147-e7b110391746.png">

**Comment by kderck** [comment]
This is still an issue.

**Comment by norosa** [comment]
@kderck thanks for responding. I will spend some time looking into this today and get back to you.

**Comment by norosa** [comment]
@kderck what version of Safari and macOS are you using?

I am using Safari 15.5 (17613.2.7.1.8) on macOS 12.4, and I have been unable to reproduce the issue.

**Comment by kderck** [comment]
I've updated Safari to (Version 15.6 (17613.3.9.1.5)) this is no longer happening.
