### ISSUE TITLE
[Fequest Request] Update Documentation 

### ISSUE THREAD

**Issue by kderck** [doitintl/help#166]
Hi DoIT, 

Please could you consider updating https://help.doit-intl.com/docs/amazon-web-services/link-account. It would be nice if this page mentioned that the resources need to be created in `us-east-1`.

**Comment by norosa** [comment]
Thanks so much for the bug report! I'm checking in with an engineer and then I'll make the change.

**Comment by norosa** [comment]
Hey, @kderck, I have a follow-up question that should allow us to better update the docs.

Were you setting up the role manually, and that's what made you realize you needed to select us-east-1?

In our screenshots, there's a "Global" option in the menu bar. If you select that, you can specify any region you like. Is this what you had to do?

Would a good fix be to add a new admonition mentioning that the user should select us-east-1 (and explain how to do that)?

If yes, where would you put it in the docs? (i.e., where would you perform that action if you were following those instructions again, knowing what you do now?)

**Comment by kderck** [comment]
Hi @norosa. If you setup manually you'll need to create `IAM Roles` and `IAM Policies`. `IAM` is Global Service that is correct. If you use the provided `CloudFormation Stacks` it's not mentioned that these need to be in `us-east-1`.
